name: 🔗 markdownlint-cli2 语法检查

# Disable automatic runs
on: [workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DavidAnson/markdownlint-cli2-action@v23
        with:
          config: '.github/.markdownlint.json'
          fix: true
          globs: |
            '**/*.md'        # 匹配所有 Markdown
            '!mu-lu.md'     # 排除单个文件
            '!README.md'     # 排除单个文件
      - name: markdownlint cli2 RP
        if: failure()
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: "Markdown 格式化"
          labels: "Markdown"
          delete-branch: true
          title: markdownlint
          body: |
            格式化——Markdown